#!/usr/bin/env bash
# Check if arg is called, then using ping with ip as argv1 to ping 5 times
if [ -z "$1" ]
  then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi
ping -c 5 $1
